print "Content-Type: text/html\n";
print "\n";
print "<html>\n";
print "<head>\n";
print "<title>test</title>\n";
print "</head>\n";
print "<body>\n";
print "This is a CGI's test.\n";
print "</body>\n";
print "</html>\n";